# Generated by Django 4.1.3 on 2022-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
