# Generated by Django 4.1.3 on 2022-12-07 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_usuario_followers_alter_usuario_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='followers',
        ),
        migrations.AddField(
            model_name='usuario',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
