# Generated by Django 4.1.3 on 2022-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_usuario_followers_usuario_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='login.usuario'),
        ),
    ]
