# Generated by Django 4.1.3 on 2022-12-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_usuario_following_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='login.usuario'),
        ),
    ]
