# Generated by Django 4.1.3 on 2022-12-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_follows_following_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='following_user_id',
            new_name='following_userid',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='userid',
        ),
    ]
