# Generated by Django 4.1.3 on 2022-12-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_follows_following_userid_alter_follows_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='following_userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='login.usuario'),
        ),
    ]
