# Generated by Django 4.1.3 on 2022-12-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_follows_following_userid_alter_follows_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='following_userid',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='userid',
            new_name='user_id',
        ),
    ]
