# Generated by Django 4.1.3 on 2022-12-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_rename_following_userid_follows_following_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
