# Generated by Django 4.1.3 on 2022-12-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
