# Generated by Django 4.1.5 on 2023-01-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
