# Generated by Django 4.1.5 on 2023-01-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_title_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_slug',
            new_name='slug_title',
        ),
    ]
