# Generated by Django 4.1.5 on 2023-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_slug_title_post_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='hello!', max_length=250, verbose_name='biography'),
        ),
    ]
